name: Build Mapmaker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make mapmaker
      run: make mapmaker
    - name: make qtl
      run: make qtl
